"""empty message

Revision ID: 42312458ed69
Revises: a51a30d6141f
Create Date: 2025-01-20 15:36:28.960211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42312458ed69'
down_revision = 'a51a30d6141f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_column('pnl')
        batch_op.drop_column('day_change')
        batch_op.drop_column('day_change_percentage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_change_percentage', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('day_change', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('pnl', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
