"""added fields email, user_type, and broker to user model

Revision ID: b707f83a95f9
Revises: 6139557845fc
Create Date: 2025-01-19 20:30:23.453100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b707f83a95f9'
down_revision = '6139557845fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('user_type', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('broker', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('broker')
        batch_op.drop_column('user_type')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
