"""empty message

Revision ID: e226c4a7707f
Revises: 081a0adec47b
Create Date: 2025-01-20 09:19:28.222649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e226c4a7707f'
down_revision = '081a0adec47b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trading_symbol', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('isin', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin'),
    sa.UniqueConstraint('trading_symbol')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stocks')
    # ### end Alembic commands ###
